# Generated by Django 5.2 on 2025-08-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_date_assignment_requested_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='sreturned_at',
            new_name='returned_at',
        ),
    ]
