# Generated by Django 5.2 on 2025-08-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_assignment_returned_at_alter_matter_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='date',
            new_name='requested_at',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='returned_at',
            new_name='sreturned_at',
        ),
    ]
