# Generated by Django 5.2 on 2025-08-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_sreturned_at_assignment_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='is_technical_issue',
            field=models.BooleanField(default=False),
        ),
    ]
